default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: <%= ENV.fetch("PG_HOST") { "localhost" } %>
  port: <%= ENV.fetch("PG_PORT") { 5432 } %>

development:
  <<: *default
  database: ecommerce_portal_development

test:
  <<: *default
  database: your_app_test

production:
  <<: *default
  database: your_app_production
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
